name: Docker Image CI

on:
  push:
    branches: [ "develop" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: |
        echo $DOCKER_TOKEN | docker login --username $DOCKER_USER --password-stdin
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile \
        --tag ${{secrets.DOCKER_USER}}/cage-app:$(date +%s) \
        --tag ${{secrets.DOCKER_USER}}/cage-app:latest

    - name: Docker Push
      run: |
        docker push ${{secrets.DOCKER_USER}}/cage-app
